#define STR_GLOBAL_OFF        0
#define STR_GLOBAL_ON         1
#define STR_GLOBAL_RESET      2
#define STR_GLOBAL_LAUNCH     3
#define STR_GLOBAL_STOP       4
#define STR_CONF_LANG         5
#define STR_LANG_RUS          6
#define STR_LANG_ENG          7
#define STR_CONF_FONT         8
#define STR_CONF_FONT_INT     9
#define STR_CONF_FONT_EXT     10
#define STR_CONF_TNT          11
#define STR_CONF_TNT_OFF      12
#define STR_CONF_TNT_PC3      13
#define STR_CONF_IRMOTDET     14
#define STR_CONF_IRMOTDET_ON  15
#define STR_CONF_IRMOTDET_OFF 16
#define STR_TIME_ALARM        17
#define STR_TIME_STOPWATCH    18
#define STR_TIME_TIMER        19
#define STR_ALARM_OFF         20
#define STR_ALARM_ON          21
#define STR_ALARM_SLEEP       22
#define STR_STOPWATCH_ON      23
#define STR_TIMER_ON          24
