#define STR_GLOBAL_0       0
#define STR_GLOBAL_OFF     1
#define STR_GLOBAL_ON      2
#define STR_GLOBAL_RESET   3
#define STR_GLOBAL_START   4
#define STR_GLOBAL_STOP    5
#define STR_CONF_LANG      6
#define STR_LANG_RUS       7
#define STR_LANG_ENG       8
#define STR_CONF_FONT      9
#define STR_CONF_FONT_INT  10
#define STR_CONF_FONT_EXT  11
#define STR_CONF_TNT_BZZZT 12
#define STR_CONF_TNT_PC3   13
#define STR_CONF_IRMOTDET  14
#define STR_TIME_ALARM     15
#define STR_TIME_STOPWATCH 16
#define STR_TIME_TIMER     17
#define STR_ALARM_SLEEP    18
#define STR_TNT_ACTION     19
#define STR_TNT_SETTINGS   20
#define STR_WEEKDAY_1      21
#define STR_WEEKDAY_2      22
#define STR_WEEKDAY_3      23
#define STR_WEEKDAY_4      24
#define STR_WEEKDAY_5      25
#define STR_WEEKDAY_6      26
#define STR_WEEKDAY_7      27
